name: Publish
env:
  # 컨텐츠를 업로드할 저장소
  BLOG_REPO: jaehunn/jaehun-blog

  # 업로드될 디렉토리 이름
  CONTENT_DIR: content
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Content
        uses: actions/checkout@v3
        with:
          path: blog-content

      - name: Check out Blog
        uses: actions/checkout@v3
        with:
          path: blog
          repository: ${{ env.BLOG_REPO }}
          token: ${{ secrets.GIT_ACTION_TOKEN }}

      - name: Install Obsidian Export
        run: |
          wget https://github.com/zoni/obsidian-export/releases/download/v22.11.0/obsidian-export_Linux-x86_64.bin
          chmod +x obsidian-export_Linux-x86_64.bin

      - name: Update Blog Content
        run: |
          rm -rf ./blog/${{ env.CONTENT_DIR }} && mkdir ./blog/${{ env.CONTENT_DIR }}
          ./obsidian-export_Linux-x86_64.bin ./blog-content/${{ env.CONTENT_DIR }} ./blog/${{ env.CONTENT_DIR }}

      - name: Commit to Blog
        run: |
          cd ./blog
          git config user.name "Jaehun"
          git config user.email "qkdwogns98@gmail.com"
          git add .
          git commit -m "Update content from Publish workflow"
          git push origin main

      - name: Remove checked out directory
        run: |
          rm -rf blog-content
          rm -rf blog
